const CHOICE_REVEAL_DELAY_MS = 300;
const PERFECT_SPOTLIGHT_DELAY_MS = 1_000;
const PERFECT_RESULT_REVEAL_DELAY_MS = 2_300;

export {
  CHOICE_REVEAL_DELAY_MS,
  PERFECT_RESULT_REVEAL_DELAY_MS,
  PERFECT_SPOTLIGHT_DELAY_MS,
};
